# Generated by Django 5.0.2 on 2024-03-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='isactive',
            new_name='is_active',
        ),
    ]
