# Generated by Django 5.0.2 on 2024-03-20 10:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_rename_isactive_banner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('phone', models.IntegerField(max_length=14, unique=True)),
                ('favicon', models.ImageField(upload_to='media/favicon')),
                ('logo', models.ImageField(upload_to='media/logo')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
    ]
