# Generated by Django 5.0.2 on 2024-03-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.IntegerField(max_length=16, unique=True),
        ),
    ]
