# Generated by Django 5.0.2 on 2024-03-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_settings_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
